[phases.setup]
nixPkgs = ["nodejs_20", "python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "python3 -m pip install --break-system-packages -r python-requirements.txt",
  "npm ci --ignore-scripts"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
